"""added rejection_reason field in KYC model

Revision ID: 2ae386c2d3eb
Revises: fe62d774da43
Create Date: 2026-07-30 09:58:47.483587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae386c2d3eb'
down_revision: Union[str, Sequence[str], None] = 'fe62d774da43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'rejection_reason')
    # ### end Alembic commands ###
