"""Changed the is_verified field's data type from String to Boolean in the KYC model

Revision ID: 89c8865497e5
Revises: e8a85ec15864
Create Date: 2026-07-26 16:28:47.492329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c8865497e5'
down_revision: Union[str, Sequence[str], None] = 'e8a85ec15864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    "kyc",
    "is_verified",
    existing_type=sa.String(),
    type_=sa.Boolean(),
    postgresql_using="is_verified::boolean",
    existing_nullable=False,
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc', 'is_verified',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
