"""Create rides table

Revision ID: a659c4a53b33
Revises: 6c13dc7310fe
Create Date: 2026-08-03 13:09:14.703832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a659c4a53b33'
down_revision: Union[str, Sequence[str], None] = '6c13dc7310fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('travel_time', sa.Time(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_index(op.f('ix_rides_ride_id'), 'rides', ['ride_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_ride_id'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###
