"""Create ride_requests table

Revision ID: b121a87b0e26
Revises: 6ed20c5bce02
Create Date: 2026-08-14 21:34:20.963117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b121a87b0e26'
down_revision: Union[str, Sequence[str], None] = '6ed20c5bce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_requests',
    sa.Column('ride_request_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('seats_requested', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.ride_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ride_request_id')
    )
    op.create_index(op.f('ix_ride_requests_ride_request_id'), 'ride_requests', ['ride_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_requests_ride_request_id'), table_name='ride_requests')
    op.drop_table('ride_requests')
    # ### end Alembic commands ###
