"""rename the field_name from rider_id to driver_id in Ride Model

Revision ID: e01b245787c7
Revises: a659c4a53b33
Create Date: 2026-08-13 19:54:03.996446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01b245787c7'
down_revision: Union[str, Sequence[str], None] = 'a659c4a53b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
