"""add route_geometry field to ride model

Revision ID: e3548ea5eb27
Revises: 75c90c7f52d0
Create Date: 2026-10-03 20:25:01.180711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3548ea5eb27'
down_revision: Union[str, Sequence[str], None] = '75c90c7f52d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('route_geometry', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'route_geometry')
    # ### end Alembic commands ###
