"""add cloudinary url and public_id fields to kyc

Revision ID: fe62d774da43
Revises: 89c8865497e5
Create Date: 2026-07-28 18:24:10.228549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe62d774da43'
down_revision: Union[str, Sequence[str], None] = '89c8865497e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('front_document_url', sa.String(), nullable=False))
    op.add_column('kyc', sa.Column('front_document_public_id', sa.String(), nullable=False))
    op.add_column('kyc', sa.Column('back_document_url', sa.String(), nullable=True))
    op.add_column('kyc', sa.Column('back_document_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'back_document_public_id')
    op.drop_column('kyc', 'back_document_url')
    op.drop_column('kyc', 'front_document_public_id')
    op.drop_column('kyc', 'front_document_url')
    # ### end Alembic commands ###
